<map version="1.0.1">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node CREATED="1584789545169" ID="ID_1829955564" MODIFIED="1584856357598" TEXT="Chapter">
<node CREATED="1584856353966" FOLDED="true" ID="ID_1162716153" MODIFIED="1584857053354" POSITION="right" TEXT="\section{Introduction}">
<node CREATED="1584856353967" ID="ID_1523409985" MODIFIED="1584856353967" TEXT="Interactions between particles are a fact of life that theory must confront in attempts to phenomena. Modern experimental techniques allow        access to a large range of interaction strengths, sometimes within otherwise identical systems. For example, optical lattices or Feshbach resonances can be used to tune interaction parameters between extreme values, from the so-called strongly correlated regime (of great interest in itself) to extremely weak or even interaction-free (?) regimes. A common element in many of these experiments is the use of Bose-Einstein        condensates (BECs) or degenerate Fermi gases as test systems for theoretical descriptions of interacting gases."/>
<node CREATED="1584856353972" ID="ID_1572228984" MODIFIED="1584856469831" TEXT="What is quantum depletion? Why is quantum depletion interesting? What is the state of current knowledge? What does this paper contribute? How did we make our measurements? How do we interpret the results in context of current research? What else should we measure to further understand?"/>
</node>
<node CREATED="1584856562369" FOLDED="true" ID="ID_1212621581" MODIFIED="1584856947313" POSITION="right" TEXT="\section{Physics of the condensed state}">
<node CREATED="1584856654090" FOLDED="true" ID="ID_188544805" MODIFIED="1584856698797" TEXT="\subsection{Properties of degenerate bose gases}">
<node CREATED="1584856353980" ID="ID_1866970147" MODIFIED="1584856688628" TEXT="The criterion for condensation is, roughly speaking, when most of the particles in a dilute bosonic gas occupy the same quantum state. More formally this is captured by the Penrose-Onsager criterion, wherein a homogeneous gas is said to be condensed if there is a macroscopic population of the ground-state eigenvalue of the ensemble density matrix. Any particles not in the ground state are said to be part of the depleted fraction. The depletion of the condensate is comprised of two parts, the thermal depletion and the quantum depletion. The thermal depletion is an artefact of the finite temperature of the condensate and has a number distribution described by Bose-Einstein statistics. The quantum depletion is a consequence of particle interactions/quantum fluctuations?"/>
</node>
<node CREATED="1584856353984" FOLDED="true" ID="ID_1144672505" MODIFIED="1584856888167" TEXT="\subsection{Bogoliubov theory and superfluidity}\label{sec:qd-introduction}">
<node CREATED="1584856353985" ID="ID_1531719867" LINK="https://www.nature.com/articles/nphys1476" MODIFIED="1584856576544" TEXT="Bose einstein condensates are like really cool. BEC was predictedby         Bose        then translated by Einstein but there&apos;s some historical controversy        here. BEC is a coherent state and connected intimately to superfluidity        - the superfluid part of a SF BEC is predicted by lookig at BE        statistics and taking the temp to zero. This means that you get lots of        bosons in the ground state - wow, loo kat that, they&apos;re all doing the        same thing! BEC is actually a measure of disorder versus        distinguishability maybe? Like you could condense at a higher        temperature if the gap is really big. BEC in a harmonic trap: Critical        temperature, condensate fraction, chemical potential, peak density,        thomas-fermi radius, momentum distribution, thermal fraction. BEC        physics: Nonlinear Schrodinger equation approximated by GPE in the        mean-field approximation BEC is actually, in practise, dependent on        interactions between atoms. They need to thermalize as you cool the        sample with evaporative cooling, although there are some folks who claim        steady-state BEC by optical cooling which doens&apos; t need th atoms to talk        to ech other. But anyway, the meanfiled part of the condensate        hamiltonian means your single particle states arent eigenstates \#\#        Context \&amp; Gap\\        Bogoliubov theory \&amp; superfluidity Connecting contact, momentum        distributions, and correlations. French disagreement Contact        measurements Probably about time to write a review paper on experiments,        no? \#\# Aim \&amp; scope\\        To reproduce the Palaiseau experiment.        Applicability of Bogoliubov theory in optical lattices https://www.nature.com/articles/nphys1476"/>
<node CREATED="1584856354036" ID="ID_777047856" MODIFIED="1584856886126" TEXT="The Bogoliubov approximation is justified whenever $n a_{s}^3$ is small, i.e. low density or weak scattering, when the depleted fraction is small.  In this case, in three dimensions, the depleted fraction is $8(n a_s ^3)^{1/2} / 3 \pi^{1/2}$ in terms of the s-wave scattering length, or $n\xi^d &gt;&gt;1$, with the healing length$\xi = \hbar/\sqrt{2mgn_c}$ and $g=4\pi \hbar^2 a_s/m$."/>
</node>
<node CREATED="1584856353988" FOLDED="true" ID="ID_1305026442" MODIFIED="1584856944688" TEXT="\subsection{Quantum depletion in degenerate gases}\label{sec:qd-history}">
<node CREATED="1584856354031" ID="ID_30661927" MODIFIED="1584856876519" TEXT="Quantum depletion is an interesting many-body phenomenon wherein repulsive interactions between atoms modify the single-particle momentum eigenstates of a Bose-Einstein condensate.  A recent experiment \cite{Chang16} observed quantum depletion in a Bose-condensed gas of helium atoms released from an optical dipole trap.  However, current theoretical understanding \cite{Qu2016} is that the depletion should not be observable after trap switch off in the presence of interactions.  To attempt to resolve this problem, we follow a similar method to \cite{Chang16}, where we observe quantum depletion of a Bose-Einstein condensate released from a magnetic trap, evident as a long tail at large momenta with the density scaling as $k^{-4}$.  The values of the Tan contact constant we measure are slightly larger than those predicted by local density theory, although the discrepancy is smaller than for the results reported in \cite{Chang16}.  Our observation suggests that the results seen here and in \cite{Chang16} are not an experimental anomaly, but rather demand deeper theoretical investigation to determine why the tails survive the trap switch-off and subsequent expansion."/>
<node CREATED="1584856353989" ID="ID_827422759" MODIFIED="1584856766262" TEXT="A Bose-Einstein condensate (BEC) forms when a system of bosons is cooled below a critical temperature, where the majority of atoms occupy the ground state of the system.  At non-zero temperature, the condensate will be depleted by thermal excitations, where some atoms occupy higher energy states with occupation probabilities following a Bose-Einstein statistics/todo{MB distribution?}.  However, even at absolute zero, the condensate will still be depleted by quantum fluctuations, a phenomenon known as quantum depletion.  The spectrum of fluctuations in the quasiparticle vacuum gives rise to an asymptotic momentum distribution that follows a $k^{-4}$ power law\cite{Qu2016}."/>
<node CREATED="1584856353992" ID="ID_253294339" MODIFIED="1584856353992" TEXT="A recent experiment \cite{Chang16} was able to see evidence of quantum depletion in the large $k$ tails of an interacting BEC released from an optical dipole trap, using the high-resolution and large dynamic range of detection offered by ultracold metastable helium atoms (He*) \cite{Vassen2012}.  A separate experiment on a strongly interacting BEC in a uniform potential probed with Bragg scattering showed that the depletion could be tuned with the interaction strength \cite{Lopes2017}."/>
<node CREATED="1584856353994" ID="ID_1368297335" MODIFIED="1584856353994" TEXT="According to current theory however, the quantum depletion seen in \cite{Chang16} is not expected to be observed, as the interactions between atoms should cause the $k^{-4}$ tails to adiabatically vanish during the expansion after trap switch off \cite{Qu2016}."/>
<node CREATED="1584856353995" ID="ID_526669324" MODIFIED="1584856814937" TEXT="During the expansion, which is taken to be hydrodynamic, the contact parameter tends to zero, which eliminates the depletion tail for sufficiently long expansions.  This viewpoint was supported by an earlier experimental result that failed to observe the tails \cite{Makotyn2014}.  However, it is unclear whether the high momentum tails, which are by definition fast moving, are in fact accurately described by this model or if their shorter interaction time with the high density region of the BEC (in a semi-classical picture) means they do in fact survive the expansion."/>
<node CREATED="1584856353998" ID="ID_696826731" MODIFIED="1584856827200" TEXT="To help resolve this discrepancy, we have conducted a similar experiment to \cite{Chang16} looking at the momentum tails of a BEC of He* released from a magnetic trap and detected after a long time of flight."/>
<node CREATED="1584856354033" ID="ID_295896338" MODIFIED="1584856354033" TEXT="The quantum depletion is a finite non-condensed fraction at zero temperature, arising from quantum fluctuations around the mean-field approximation to the condensate. The deformation of the condensate by the mean-field term in the GP equation does not lead to depletion. The authors comment that the depleted fraction may be \emph{less}, and not \emph{more} quantum than the condensate. Nonetheless: the depletion that follows is the quantum depletion as opposed to the thermal depletion: It is given by integrating the momentum fluctuations"/>
<node CREATED="1584856354035" ID="ID_1476004411" MODIFIED="1584856354035" TEXT="$$\delta n = L^{-d} \sum_{\textbf{k}} \delta n_{\textbf{k}}$$"/>
</node>
</node>
<node CREATED="1584856354135" FOLDED="true" ID="ID_1282233754" MODIFIED="1584857004220" POSITION="right" TEXT="\section{Methods}\label{methods}">
<node CREATED="1584856354136" MODIFIED="1584856354136" TEXT="Our experiments start with a condensate of helium atoms in the          $M_J = +1$  state of the metastable  $2^3 S_1$  manifold in a BiQUIC        magnetic trap \begin{equation}Dall2007\end{equation}. We use two trap configurations with         characteristic frequencies  $\sim 2\pi\cdot (312,312,52)$  and         $2\pi\cdot 666,666,69)$  Hz. The trap is switched off in         $\sim 100\mu s$  and the atoms allowed to fall 48mm, where they are        detected with a multi-channel plate and delay line detector        \begin{equation}Manning2010\end{equation}. To avoid distortion of the condensate by stray        magnetic fields, we transferred approximately 25 -  of the condensate        into the magnetically insensitive  $M_J=0$  state by applying a chirped        sine wave 2ms after trap switch-off, swept from 1.6 to 2.6 MHz in 1ms,        while a DC magnetic field remained on to preserve the Zeeman splitting        between  $M_J = {0,\pm 1}$  states. A magnetic field gradient is        switched on after the state transfer pulse, which ensures the        magnetically sensitive  $M_J = \pm 1$  states are deflected enough to        miss the detector. We varied total atom number between X and         $Y\times 10^5$  atoms per condensate by varying the endpoint of the        evaporative cooling ramp."/>
<node CREATED="1584856354138" MODIFIED="1584856354138" TEXT="After release from the trap the atoms expand ballistically into the        far-field regime, where their position on the detector corresponds to        their momentum at trap release. Therefore we can reconstruct the        far-field momentum distribution  $n^*(\textbf{k})$  from our detector        data. The observed momentum profile  $n^*(\textbf{k})$  cannot be identified completely with the in-trap momentum distribution         $n_0(\textbf{k})$  as repulsive interatomic forces distort the profile        immediately after release from the trap. Structure is visible over five        orders of magnitude in density, comprised of the condensed, thermal, and        depleted fraction before the signal drops below the dark-count        background noise. There is some saturation evident around the low        momentum values due to the high atom flux during BEC impact. Our        analysis does not include this part of the momentum profile, and we find        evidence that saturation is only an issue during the peak flux, not in        the thermal or depleted fractions."/>
<node CREATED="1584856354141" MODIFIED="1584856354141" TEXT="Since for these experiments a precise knowledge of the total atom number        and trap frequency is important, we measure the trapped population and        trapping frequency at regular intervals throughout each experimental        run, using a procedure that avoids detector saturation to measure the        atom number and precise determination of the trap frequency. We        identified a contamination of the depletion signal by stray counts        attributable to the m=+1 state, and calibrate for this by including        shots without the RF transfer step. We also apply corrections for the        detector dark count rate and an increased background rate on the leading        edge of the condensate (details about the calibration are included in        the supplementary materials)        Our experiments start with a condensate of helium atoms in the         $M_J = +1$  state of the metastable  $2^3 S_1$  manifold in a BiQUIC        magnetic trap \begin{equation}Dall2007\end{equation}. We use two trap configurations with        characteristic frequencies  $\sim 2\pi\cdot (312,312,52)$  and         $2\pi\cdot 666,666,69)$  Hz. The trap is switched off in         $\sim 100\mu s$  and the atoms allowed to fall 48mm, where they are        detected with a multi-channel plate and delay line detector        \begin{equation}Manning2010\end{equation}. To avoid distortion of the condensate by stray        magnetic fields, we transferred approximately 25 -  of the condensate        into the magnetically insensitive  $M_J=0$  state by applying a chirped        sine wave 2ms after trap switch-off, swept from 1.6 to 2.6 MHz in 1ms,        while a DC magnetic field remained on to preserve the Zeeman splitting        between  $M_J = {0,\pm 1}$  states. A magnetic field gradient is        switched on after the state transfer pulse, which ensures the        magnetically sensitive  $M_J = \pm 1$  states are deflected enough to        miss the detector. We varied total atom number between X and         $Y\times 10^5$  atoms per condensate by varying the endpoint of the        evaporative cooling ramp."/>
<node CREATED="1584856354144" MODIFIED="1584856354144" TEXT="After release from the trap the atoms expand ballistically into the        far-field regime, where their position on the detector corresponds to        their momentum at trap release. Therefore we can reconstruct the        far-field momentum distribution  $n^*(\textbf{k})$  from our detector        data. The observed momentum profile  $n^*(\textbf{k})$  cannot be        identified completely with the in-trap momentum distribution         $n_0(\textbf{k})$  as repulsive interatomic forces distort the profile        immediately after release from the trap. Structure is visible over five        orders of magnitude in density, comprised of the condensed, thermal, and        depleted fraction before the signal drops below the dark-count        background noise. There is some saturation evident around the low        momentum values due to the high atom flux during BEC impact. Our        analysis does not include this part of the momentum profile, and we find        evidence that saturation is only an issue during the peak flux, not in        the thermal or depleted fractions."/>
<node CREATED="1584856354145" MODIFIED="1584856354145" TEXT="Since for these experiments a precise knowledge of the total atom number        and trap frequency is important, we measure the trapped population and        trapping frequency at regular intervals throughout each experimental        run, using a procedure that avoids detector saturation to measure the        atom number and precise determination of the trap frequency. We        identified a contamination of the depletion signal by stray counts        attributable to the m=+1 state, and calibrate for this by including        shots without the RF transfer step. We also apply corrections for the        detector dark count rate and an increased background rate on the leading        edge of the condensate (details about the calibration are included in        the supplementary materials)"/>
<node CREATED="1584856354147" MODIFIED="1584856354147" TEXT="\subsection{Determination of the Tan constant}\label{ssec:qd-processing}"/>
<node CREATED="1584856354148" MODIFIED="1584856354148" TEXT="The RF pulse may increase the Penning ionization rate in the depolarized        sample, even though the density is low, which would alter the momentum        profile. While applying the magnetic separation pulse, the condensates        may scatter off each other."/>
<node CREATED="1584856354150" MODIFIED="1584856354150" TEXT="\begin{figure}"/>
<node CREATED="1584856354151" MODIFIED="1584856354151" TEXT="\includegraphics[width=\textwidth]{fig/depletion/include/frac_cal.eps}"/>
<node CREATED="1584856354152" MODIFIED="1584856354152" TEXT="\label{fig:qd-fraction_calibration}"/>
<node CREATED="1584856354154" MODIFIED="1584856354154" TEXT="\caption"/>
<node CREATED="1584856354155" MODIFIED="1584856354155" TEXT="\title"/>
<node CREATED="1584856354156" MODIFIED="1584856354156" TEXT="\end{figure}"/>
<node CREATED="1584856354157" MODIFIED="1584856354157" TEXT="\begin{figure}"/>
<node CREATED="1584856354158" MODIFIED="1584856354158" TEXT="\includegraphics[width=\textwidth]{fig/depletion/include/partition_QD_files_profile_overlay_st.eps}"/>
<node CREATED="1584856354159" MODIFIED="1584856354159" TEXT="\end{figure}"/>
<node CREATED="1584856354160" MODIFIED="1584856354160" TEXT="\begin{figure}"/>
<node CREATED="1584856354161" MODIFIED="1584856354161" TEXT="\includegraphics[width=\textwidth]{fig/depletion/include/partition_QD_files_profile_overlay_hf.eps}"/>
<node CREATED="1584856354163" MODIFIED="1584856354163" TEXT="\end{figure}"/>
<node CREATED="1584856354164" MODIFIED="1584856354164" TEXT="The Tan contact parameter is extracted by a fit to BEC density profile        after subtracting the calibrated noise profiles. The functional form        includes contributions from the thermal fraction and depleted fraction        and includes the free parameters  $N_{th}$  the number of thermal atoms,         $\lambda_{dB} = h/\sqrt{2\pi m k_B T}$  the thermal de Brogliewavelength, and  $C$  is the scale of the fitted power law."/>
<node CREATED="1584856354165" MODIFIED="1584856354165" TEXT="FIGS Experimental sequence \#\# Results"/>
<node CREATED="1584856354166" MODIFIED="1584856354166" TEXT="FIGS: Condensate density profile \&amp; scaled, with fit Contact vs Density"/>
<node CREATED="1584856354167" MODIFIED="1584856354167" TEXT="plot"/>
<node CREATED="1584856354168" MODIFIED="1584856354168" TEXT="\subsubsection{Flux model}"/>
<node CREATED="1584856354169" MODIFIED="1584856354169" TEXT="In the image obtained from the MCP-DLD detector of the shots in which        the quantum depletion is observed, the pointwise density of atom        detection events in momentum space can be described by"/>
<node CREATED="1584856354171" MODIFIED="1584856354171" TEXT="$$ n(\textbf{k}) = \sum{m=1}^3 nm(\textbf{k},N,\omega{x,y,z},T) + \delta(\textbf{k}) + \lambda(N0,\bar{\omega}\textbf{k})\Theta(-kz) $$"/>
<node CREATED="1584856354172" MODIFIED="1584856354172" TEXT="The first terms nm refer to the detected density of atoms from        the$mJ=m$condensates, which depends on the momentum vector $\textbf{k}$ on        the total atom number N , the temperature  T , and harmonic trapping        frequencies$\omega{x,y,z}$. The dark count rate $\delta$ is        momentum-dependent due to its non-uniformity on the detector. The        measured trap leak rate$\lambda $stops when the trap is released, hence        the Heaviside$\Theta$ function ensures this term only contributes on the        lower side of the falling BEC. Below we adopt the        notation $\delta+\lambda  = \delta +\lambda\Theta \theta  $        where$\theta$ is the elevation angle from the plane        of the detector subtending from the centre of the condensate. Details of        the measurement and calibration of each of these terms is discussed in        section calibration."/>
</node>
<node CREATED="1584856354067" FOLDED="true" ID="ID_1416208298" MODIFIED="1584857049540" POSITION="right" TEXT="\subsection{Detection of ultradilute momentum spectra}\label{ssec:qd-model}">
<node CREATED="1584856354068" MODIFIED="1584856354068" TEXT="\begin{figure}"/>
<node CREATED="1584856354071" MODIFIED="1584856354071" TEXT="\includegraphics[width=\textwidth]{fig/depletion/include/partition_QD_files_01_shot_counts_combine.eps}"/>
<node CREATED="1584856354072" MODIFIED="1584856354072" TEXT="\label{fig:qd-count_by_type}"/>
<node CREATED="1584856354073" MODIFIED="1584856354073" TEXT="\caption"/>
<node CREATED="1584856354074" MODIFIED="1584856354074" TEXT="\title"/>
<node CREATED="1584856354075" MODIFIED="1584856354075" TEXT="\end{figure}"/>
<node CREATED="1584856354076" MODIFIED="1584856354076" TEXT="\begin{figure}"/>
<node CREATED="1584856354077" MODIFIED="1584856354077" TEXT="\includegraphics[width=\textwidth]{fig/depletion/include/calibrate_QD_shots_01_stats.eps}"/>
<node CREATED="1584856354078" MODIFIED="1584856354078" TEXT="\label{fig:qd-n0_by_time}"/>
<node CREATED="1584856354079" MODIFIED="1584856354079" TEXT="\caption"/>
<node CREATED="1584856354079" MODIFIED="1584856354079" TEXT="\title"/>
<node CREATED="1584856354080" MODIFIED="1584856354080" TEXT="\end{figure}"/>
<node CREATED="1584856354081" MODIFIED="1584856354081" TEXT="Average dark count rate is determined to be(5.6228E3 Hz/m$^2$),        or(9.3713E-16 $m(-1)(-3)$. The latter is        calculated by converting 1 sec interval into a distance c.f. the centre        of mass velocity of the BEC - about 4m or 4E6 micron. Sequence \&amp;        Calibration stages Total number"/>
<node CREATED="1584856354083" MODIFIED="1584856354083" TEXT="Well this isn&apos;t anything new, I just use the pulsed atom laser in the        same way as other chapters. Because I care more about number here I&apos;d        like to spend a bit of time thinknig about number errors that could crop        up here which are perhaps less important to treat than they are in        tuneout, which will be a busy chapter in its own right. Raw profiles"/>
<node CREATED="1584856354085" MODIFIED="1584856354085" TEXT="Centering algorithm to align BECs and compile to single shot. Create        histogram in spherical coordinates. Compile and apply calibration        corrections. Do some fancy fitting - theory-driven pre guesses T from        fits and consistnency Trap leakage"/>
<node CREATED="1584856354087" MODIFIED="1584856354087" TEXT="Trap leakage is surely number-dependent. Who knows what the law actually        is - there is probably some combination of majorana and ??? - perhaps        could ballpark what the leak rate should be, see if it squares with what        I observe. But yeah it results in an increased flux rate, you can see it        in the time trace. The best way to deal with it would be to extend the        hold for ages, and then get heaps of statistics, but in the end I wound        up using the 20-odd ms window of hold before drop in each case. This        still gets to within ??? some margin of error when using all the data I        have for a given run. Given the small count rate it isn;t at all obvious        that I would be able to do this shot-for-shot; not sure what type of        noise this is. Background"/>
<node CREATED="1584856354088" MODIFIED="1584856354088" TEXT="This one was easy. I just took the dark count rate from everywhere else;        make a histogram displaced on the detector, assuming the dark counts and        hotspots are time invariant. Are they? Worth a look I guess. But this is        just like camera dark-fielding. That could be a great analogy actually!        There are three channels, some background, and, well, the leakage but        whatever let&apos;s sort of ignore that. Let&apos;s show it&apos;s Poissonian, maybe?        Just to show that it really is uncorrelated events? Spin mixing"/>
<node CREATED="1584856354091" MODIFIED="1584856354091" TEXT="Well, this one was OK, I just ran the experiment without the transfer.        It shows up fine, I used the center found in the AVERAGE (I think) which        might be worth looking at - should it be better to use the centre fixed        from the proximate shots? idk. Depends on whether there&apos;s genuine drift        or just jitter in BEC arrival position. Lol, I guess one could do an        allan variance of this one also, that would tell you the best period to        average across. Actually, yeah that is kind of cool. Perhaps including        that much detail in the `possible improvements&apos; part. The origin of this        isn&apos;t clear, hey. It is unlikely to be m=1 atoms, honestly, as they        would probably be movable with the Z coil after the `spray&apos;. The spray        moment suggests it&apos;s something in the fall path that seems to be an        issue - one can control a little bit where it impacts by adjusting push        coil timigns - but never quite entirely get rid of it. There is also the        question of the m=-1 atoms floating around. But then, calibrating for        that would involve using a different RF sequence, perhaps, and at the        end of the day maybe the best thing to do would be to find a Rabi        transfer setup that pushed everything into M=0 anyhow, and see whether        the symmetry is a problem there. Something I&apos;d like to do is to drop an        entire BEC, center it very carefully and then reflect it in 3D, and        subtract histograms. But that&apos;s a mini project for another time and        might not really demonstrate much. I would need to include at this point        an argument to gauge the systematic error, for example by spreading the        entire population uniformly or worst-case just in the power law. Then        see how much a difference that woudl make. Transfer fraction calibration"/>
<node CREATED="1584856354093" MODIFIED="1584856354093" TEXT="Verification that saturation is not a thing - also kinda pulls out the        flux rate wehre saturation is a problem (could do this in 3D, obvs        nonlinear but whatever, it&apos;s a ballpark) Verifies that m=0 halo is not        distorted significantly in the transfer process Verifies that at least        within the thermal part, no k-dependence of transfer Model of sweep -        would it have been practical to get the max transfer without any        momentum-dependences? - what is the doppler shift of the depleted atoms,        anyhow? Not to mention the RF field is certainly not spatially coherent        hey How accurately is this determined?"/>
<node CREATED="1584856354096" MODIFIED="1584856354096" TEXT="Processing"/>
<node CREATED="1584856354097" MODIFIED="1584856354097" TEXT="My general dream for these sections is a graph of the program or some        kind of systems diagram, maybe nested screenshots or pseudocode would do        the trick and then include the code as an appendix hey?">
<node CREATED="1584856354099" MODIFIED="1584856354099" TEXT="\subsubsection{Contributions to the model}"/>
</node>
<node CREATED="1584856354100" ID="ID_630879453" MODIFIED="1584856354100" TEXT="The count density from the falling BECs depend explicitly on the trapped        population and on the trapping frequencies. This is most obviously true        for the condensate of atoms in the(mJ=0)state, and also for        the$mJ=\pm 1$condensates when all three condensates land undisturbed on        the detector during calibration of the transfer efficiency."/>
<node CREATED="1584856354102" ID="ID_386072052" MODIFIED="1584856354102" TEXT="In the depletion detection shots, we have observed a remaining presence        of(mJ=1)atoms, the cause of which is unclear but is suspected to be due        to a collision process with a feature inside the chamber. Regardless of        the cause, we calibrate for this contamination (also called        \textit{spin mixing} elsewhere). The count density of the(mJ=1)states        depends on the trapping frequencies also - this could be because the        trap centre shifts with changing trap frequencies, changing the details        of the spin mixing process during freefall. We cannot rule out the        presence of(mJ=-1)on the detector also. Calibrating for this        contribution is less straightforward, as discussed below. The        temperature dependence of the condensate density is expected to manifest        only as a change in the thermal fraction - calculation of the thermal        depletion contributions are pending."/>
<node CREATED="1584856354104" MODIFIED="1584856354104" TEXT="The contributions from the dark count rate are assumed to be        time-invariant and independent of any properties of the condensate        itself. There may be a change in the dark count rate while the detector        is subject to high atom fluxes, but these are not expected to be a        problem for the following reasons: One, we observe very similar thermal        tails both above and below the condensate, suggesting that, at least,        the quantum efficiency and dark count rates are not significantly        different. Two, although there are some temporary hotspots on the        detector during the peak BEC flux, these are only observed co-temporally        with the falling BEC. The quantum depletion is detected far beyond the        regions where this effect is noticable, and so they are not expected to        contaminate the signal."/>
<node CREATED="1584856354106" MODIFIED="1584856354106" TEXT="The leak rate should be expected to be dependent on the BEC number. The        most simple model would be an exponential decay of BEC number with some        collection efficiency by the detector. There may also be        density-dependent collision effects feeding the trap leak rate driven by        changing the trapping frequencies, which could also alter any spatial        structure in the leak rate due to a shift in trap position.        Our experiments start with a condensate of helium atoms in the $M_J = +1$ state of the metastable $2^3 S_1$ manifold in a BiQUIC magnetic trap \cite{Dall2007}. The trap is switched off in $\sim 100\mu s$ and the atoms allowed to fall 848mm, where they are detected with a multi-channel plate and delay line detector \cite{Manning2010}.  To reduce the detector saturation, 2ms after trap switch-off we transferred approximately 43 -  of the condensate into the magnetically insensitive $M_J=0$ state by applying a chirped sine wave, swept from 1.6 to 2.6 MHz in 1ms, while a DC magnetic field remained on to preserve the Zeeman splitting between $M_J = {0,\pm 1}$ states.  A magnetic field gradient is switched on 5ms after the state transfer pulse, which ensures the magnetically sensitive $M_J = \pm 1$ states are deflected enough to miss the detector."/>
<node CREATED="1584856354109" MODIFIED="1584856354109" TEXT="After release from the trap the atoms expand ballistically into the far-field regime, where their position on the detector corresponds to their momentum after trap release by $\textbf{k} = m\textbf{r}/\hbar t_{tof}$, where $t_{tof}$ is the fall time to the detector. Therefore we can reconstruct the far-field momentum distribution $n^*(\textbf{k})$ from our detector data. The observed momentum profile $n^*(\textbf{k})$ cannot be identified completely with the in-trap momentum distribution $n_0(\textbf{k})$ as repulsive interatomic forces distort the profile immediately after release from the trap. {{red}Is this basically the argument for why we see the increased depletion?}"/>
<node CREATED="1584856354110" MODIFIED="1584856354110" TEXT="% \com{[Has anyone actually modeled/measured this?]}"/>
<node CREATED="1584856354111" MODIFIED="1584856354111" TEXT="As in \cite{Chang16} we find the large-$\textbf{k}$ momentum distribution is isotropic, unlike the in-trap mean-field interactions, and conclude that the extreme momenta are not strongly affected by the mean-field."/>
<node CREATED="1584856354113" MODIFIED="1584856354113" TEXT="A typical condensate profile shown in Fig. \ref{k_profile}.  Structure is visible over five orders of magnitude in density, comprised of the condensed, thermal, and depleted fraction before the signal drops below the dark-count background noise. There is some saturation evident around the low momentum values due to the high atom flux during BEC impact, however this part of the histogram is not used for the analysis."/>
<node CREATED="1584856354115" MODIFIED="1584856354115" TEXT="To investigate the behaviour of the depletion over a wide range of system parameters, we used traps with two different configurations as well as different total atom numbers:  One trap configuration characteristic frequencies $ \sim 2\pi\cdot (312,312,52)$ and the other with $\sim 2\pi\cdot (476,476,66)$ Hz. Since for these experiments a precise knowledge of the total atom number and trap frequency is important, we developed an experimental procedure to regularly calibrate the trapped population and trapping frequency at regular intervals throughout each experimental run, using a procedure that avoids detector saturation to measure the atom number (see supplementary material).  We varied total atom number  between 1 and $5\times 10^5$ atoms per condensate by varying the endpoint of the evaporative cooling ramp."/>
<node CREATED="1584856354117" MODIFIED="1584856354117" TEXT="The depletion is a feature of the condensed atoms in the ground state, and expected to be unaffected by the changes in temperature.   {{red}However, the contact is temperature-dependent, how important is it expected to be?} As shown in Fig \ref{C_inf}, the quantum-depleted population is affected by the trap frequencies and population only inasmuch as they determine the peak density."/>
<node CREATED="1584856354119" MODIFIED="1584856354119" TEXT="We operated our traps in a constant DC bias field to maintain the Zeeman splitting between the $M_J$ states, which is required for the RF transfer sequence detailed below. Our measurements were made by a delay-line detector placed 848mm below the condensate, upon which the condensate lands after expanding into the far-field regime in free-fall through the vacuum chamber. with a magnetically trapped BEC and additional calibration of the condensate population and density.">
<node CREATED="1584856354121" MODIFIED="1584856354121" TEXT="- Our bespoke software interfaces with the LabView control environmentand loops over a sequence of experiments, consisting in this case of:        Atom number calibration, Trap frequency calibration, and RF transfer        efficiency, followed by 10 data collection runs."/>
<node CREATED="1584856354123" MODIFIED="1584856354123" TEXT="- To calibrate the atom number, we used an RF pulse sequence to create a        pulsed atom laser with intensity well below the saturation threshold of        our delay-line detector. We corrected the number of detected atoms to        account for the quantum efficiency ($\sim$8 - ) of our detector.         - {blue}{Should use QD measurements to compute condensate/thermal fraction relative sizes and further improve $N_0$ measurement}.         - {blue}{how does this compare to our trap binning? What is the uncertainty of the QE?}"/>
<node CREATED="1584856354130" MODIFIED="1584856354130" TEXT="- Together with the atom number, a measurement of the centre-of-mass        motional frequencies allowed us to compute the peak density of the        condensate. We measured the trap frequency by transient magnetic fieldto the trapped condensate for $\sim 150\mu s$, forcing centre-of-mass        motion in the lab frame. We used the same pulsed outcoupling scheme as        in the number measurement, and measured the centre-of-mass momentum of        the cloud at the time of each pulse. Our outcoupling frequency is well        below the natural frequency of the confining potential so we used a        subsampled reconstruction method to recover the trap frequency. Prior to        running experiments we varied the outcoupling pulse frequency to        determine in which Nyquist zone the actual trap frequency lies relative        to our sampling frequency. We can then obtain the trap frequency to        within precision X in a single shot of the experiment by taking a        Fourier transform of the centre of mass motion."/>
<node CREATED="1584856354133" MODIFIED="1584856354133" TEXT="- Our calibration sequence provided accurate number and peak density        measurements along with the condensate profile. We verified the        spherical symmetry of the thermal and depleted fractions, and so compute        the momentum density by an average over a large section of the momentum        distribution."/>
</node>
</node>
<node CREATED="1584856354042" FOLDED="true" ID="ID_673824922" MODIFIED="1584857046183" POSITION="right" TEXT="\section{Measurement of the universal Tan constant}\label{sec:qd-method}">
<node CREATED="1584856354043" ID="ID_307250740" MODIFIED="1584856354043" TEXT="We assume that the RF pulse and magnetic separation of the condensates        does not affect their far-field distribution. This may be false if the        inter-condensate scattering rate is high (calculation/reference        pending). The RF pulse transfers atoms into the different(mJ)states with        efficiency$\eta_J$, therefore we estimate the momentum density of the        initial condensate via"/>
<node CREATED="1584856354045" ID="ID_764177451" MODIFIED="1584856354045" TEXT="% [n(k) = \frac{1}{\eta0}\left(\bar{n}0 - \eta1\bar{n}1 -1+\eta1)(\delta+\lambda)\right)]"/>
<node CREATED="1584856354046" ID="ID_49063366" MODIFIED="1584856354046" TEXT="where (n{1) refer respectively to the count densities        obtained from the measurement and spin mixing calibration shots. We        produce a background calibration for$(\delta+\lambda)$by defining        background density in the upper and lower hemisphere        of$\bar\delta\pm$to be the backgrounds obtained from the dark count        and leak calibrations, respectively. We determined the transfer        efficiencies$\eta_J$from the initially released condensate to the        other$mJ$states by separating the clouds with a magnetic field gradient        generated by auxiliary field coils. (Refinement pending). We calibrate        the dark count rate by building a spherical histogram centred at the        same position on the detector as the(mJ=0)condensate, but 2 seconds        after the condensate impact and before the trap loading sequence begins,        and calibrate the trap leak similarly but centering the histogram about        a point earlier in time than the BEC impact. We calibrate the        contamination by stray(mJ=1)counts by running the depletion measurement        sequence without the RF transfer, obtaining the distribution of stray        counts, plus the background count rate. By subtracting our empirical        measurement of the background, we obtain the estimated density of the        stray counts,$n1 = \bar{n}1 - (\delta+\lambda)$."/>
<node CREATED="1584856354048" ID="ID_1294788575" MODIFIED="1584856354048" TEXT="The total atom number(N)and trapping frequencies$\omega i$are determinedby a pulsed atom-laser measurement, which we describe in detail in        another publication. A fit of the empirical thermal fraction        produces a measurement of the temperature, through which we may        determine the condensed number(N0)."/>
<node CREATED="1584856354050" ID="ID_150405364" MODIFIED="1584856354050" TEXT="The Tan contact parameter is extracted by a fit to BEC density profile        after subtracting the calibrated noise profiles. The functional form        includes contributions from the thermal fraction and depleted fraction        and includes the free parameters  $N_{th}$  the number of thermal atoms,         $\lambda_{dB} = h/\sqrt{2\pi m k_B T}$  the thermal de Broglie        wavelength, and  $C$  is the scale of the fitted power law."/>
<node CREATED="1584856354052" ID="ID_1436086851" MODIFIED="1584856354052" TEXT="According to theoretical predictions based on the local density        approximation \begin{equation}Chang16\end{equation}, the contact constant  $C_{LDA}$  of the        depleted fraction should vary linearly with the peak condensate density         $n_0$ . This was found in previous experiments\begin{equation}Chang16\end{equation}, although        their scaling factor greater by a factor of $\sim$6.5. In Fig. XX, we        plot our measured values of  $C$  and  $n_0$ , identifying the fit        parameter  $C$  with the contact constant  $C_{LDA}$ . A linear fit to        the contact constant variation finds a gradient approximately 1.7 times        more than the theory predicts, closer to theory than the previous        measurement"/>
<node CREATED="1584856354054" ID="ID_799289724" MODIFIED="1584856354054" TEXT="The quantum depletion is extracted following a similar procedure to Chang et al \cite{Chang16} to fit the data outside the central BEC with a functional form that includes contributions from the thermal fraction, depleted fraction, as well as a constant background due to detector background counts.  We transform the histogram data by $n&apos;(\textbf{k}) = |\textbf{k}|^4\times n^*(\textbf{k})$ and fit with the function $n_{fit}(k)\times k^4$, where"/>
<node CREATED="1584856354056" ID="ID_346753618" MODIFIED="1584856354056" TEXT="$$">
<node CREATED="1584856354057" ID="ID_770463580" MODIFIED="1584856354057" TEXT="n_{fit}(k) = \frac{N_{th}g_{3/2}exp(-k^2 \lambda_{dB} ^2 /4\pi)}{1.202(2\pi/\lambda_{dB})^3} + \frac{C}{(2\pi)^3 k^4} + const,">
<node CREATED="1584856354059" ID="ID_1912374076" MODIFIED="1584856354059" TEXT="$$"/>
</node>
</node>
<node CREATED="1584856354060" ID="ID_1749267336" MODIFIED="1584856354060" TEXT="with four free parameters: $N_{th}$ the number of thermal atoms, $\lambda_{dB} = h/\sqrt{2\pi m k_B T}$ the thermal de Broglie wavelength, $const$  a constant to account for the detector background count rate, and $C$ is the scale of the fitted power law assumed to correspond to the Tan contact parameter. In the local density approximation, $C \approx C_{LDA} = \int d\textbf{r} [16\pi^2 \rho^2(\textbf{r},t)a^2]$, where $a$ is the scattering length and $\rho$ the atomic density."/>
<node CREATED="1584856354062" ID="ID_1825268105" MODIFIED="1584856354062" TEXT="redVerify fitting is faithful estimator; examine bias and stability for unconstrained powers"/>
<node CREATED="1584856354063" ID="ID_1205372857" MODIFIED="1584856354063" TEXT="% \com{[Keeping the power law exponent as a free parameter, rather than fixing it at 4, has not so far been successful]}"/>
<node CREATED="1584856354065" ID="ID_652661638" MODIFIED="1584856354065" TEXT="The fit is shown in Fig. \ref{k_profile} as a green line, and is seen to agree with the data well.  This good agreement and fit robustness is due to each of the three contributions dominating at a distinctly separate range of $k$ values.         - We verified the fitting method by analysing a test data set of known        parameters, which was generated by the Metropolis-Hastings algorithm,        and find the method recovers the test set parameters within a factorless than our experimental uncertainties."/>
<node CREATED="1584856354177" ID="ID_951073480" MODIFIED="1584857021687" TEXT="The far-field density of a harmonically trapped condensate is described         by contributions from the condensed, thermal, and depleted populations,"/>
<node CREATED="1584856354179" ID="ID_180367507" MODIFIED="1584857021689" TEXT="\begin{equation} n(\textbf{k}) = n{BEC}(\textbf{k}) + n{T}(\textbf{k}). \end{equation}"/>
<node CREATED="1584856354180" ID="ID_1614553245" MODIFIED="1584857021691" TEXT="The momentum density of the thermal fraction is [Pitaevskii \&amp; Stringari]"/>
<node CREATED="1584856354181" ID="ID_1272385278" MODIFIED="1584857021694" TEXT="\begin{equation}">
<node CREATED="1584856354182" MODIFIED="1584856354182" TEXT="n{T}\textbf{k} =\frac{1}{\left(\lambda T m \bar{\omega}\right)^3}"/>
</node>
<node CREATED="1584856354183" ID="ID_577434732" MODIFIED="1584857021697" TEXT="\end{equation}"/>
<node CREATED="1584856354184" ID="ID_382329251" MODIFIED="1584857021699" TEXT="\begin{equation}"/>
<node CREATED="1584856354185" ID="ID_529738281" MODIFIED="1584857021700" TEXT="g^{3/2}\left(e^{{-\beta} k^2/2m\hbar^2}\right)"/>
<node CREATED="1584856354186" ID="ID_1347455443" MODIFIED="1584857021701" TEXT="\end{equation}"/>
<node CREATED="1584856354187" ID="ID_1788082277" MODIFIED="1584857021703" TEXT="where $T$is the temperature,$\lambda T = h^2/\sqrt{2\pi m kB T}$is the        thermal de Broglie wavelength,$\bar{\omega}$is the geometric mean of        the trapping frequencies,$\beta=1/ kB T$is the thermodynamic Beta,        and$g{3/2}(z)$is the Bose integral"/>
<node CREATED="1584856354189" ID="ID_1421557299" MODIFIED="1584857021707" TEXT="\begin{equation}"/>
<node CREATED="1584856354189" ID="ID_705617494" MODIFIED="1584857021709" TEXT="g^{3/2}(z) =\frac{2}{\sqrt{\pi}}\int 0^{\infty} \frac{\sqrt{x}}{z^{-1}e^x-1}=\sum{l=1}^{\infty} \frac{z^l}{3/2}."/>
<node CREATED="1584856354191" ID="ID_77952136" MODIFIED="1584857021710" TEXT="\end{equation}"/>
<node CREATED="1584856354191" ID="ID_1904826492" MODIFIED="1584857021712" TEXT="The short-wavelength density of the BEC momentum density is described by        the Thomas-Fermi approximation. The asymptotic momentum distribution is        that of the quantum depletion, \begin{equation} n(\textbf{k}) =        \frac{C\infty}{(2\pi)^3 k^4}, \end{equation}"/>
<node CREATED="1584856354193" ID="ID_1929049414" MODIFIED="1584857021715" TEXT="where$C\infty$is the universal Tan constant, defined by$\mathcal{C}{\infty}=\textrm{lim}{ \extbf{k} \to\infty}(2\pi)^3 \textbf{k} ^4 n(\textbf{k})$,        and for a        harmonically trapped Bose gas is $\frac{64\pi^2}{7}a{s}^{2}N0n0$        in the local density approximation Chang et al"/>
<node CREATED="1584856354194" ID="ID_1471800295" MODIFIED="1584857021717" TEXT="The asymptotic behaviour of the single-particle probability density        function for a particle in the ground state (not in the thermal        fraction) is therefore$\frac{64\pi^2}{7}a{s}^{2} n0$, hence the        contact constant can be seen as a parameter defining a probability        distribution, which we estimate using the procedure described in the        next section."/>
</node>
<node CREATED="1584856354196" FOLDED="true" ID="ID_1111244663" MODIFIED="1584857040209" POSITION="right" TEXT="\section{Discussion}\label{qd-discussion}">
<node CREATED="1584856354198" MODIFIED="1584856354198" TEXT="This suggests that the originally observed result is indeed a real        physical effect rather than experimental error. Hopefully our result        will stimulate new theoretical interest in developing an explanation of        why the quantum depletion tails can be observed after an interacting        expansion, as well as try to resolve the discrepancy with theory."/>
<node CREATED="1584856354201" MODIFIED="1584856354201" TEXT="A possible future experimental extension is to outcouple atoms using a        broadened Raman transition. This would have the benefit of moving the        outcoupled atoms through the cloud rapidly, minimising the effects of        repulsive inter-atomic interactions that normally affect the outcoupled        profiles. This should shed some light on whether interactions during        trap switch off are the origin of the momentum tails. One could test the        importance of particle scattering or Penning ionization by delaying the        Rabi transfer to the  $M_J = 0$  state, but this could increase        vulnerability to stray magnetic fields. There is scope to optimize the        RF transfer sequence to achieve much higher transfer efficiency for a stronger signal. \#\# Issues\\        Sys: Background Stat: Fitting power laws, weak signals \#\# Method\\        \# Supplementary materials"/>
<node CREATED="1584856354203" MODIFIED="1584856354203" TEXT="FIGS Combined time profiles Thermal transfer calibration Interleaving        sequence - main text?        There are some possible explanations for the disagreement between LDA        theory and experiment. This experiment requires resolution of a strong        signal over nearly five orders of magnitude, careful calibration, and        accurate parameter estimation with sparse and noisy data, and power-law        fits are notoriously difficult."/>
<node CREATED="1584856354205" MODIFIED="1584856354205" TEXT="Across all datasets, we find that fitting procedure outlined above yields a power law exponent of $\alpha = -X.X(X)$         Actually, I only fitted with $\alpha$=4. We should chat about this method in detail. By analysis of residuals, the fit errors appear random. This is a very weak claim - needs bolstering for final paper, or omission here. This suggests that the profile consists of a thermal fraction, the background count contribution, and a quantum depleted fraction that is consistent with a power law with exponent X"/>
<node CREATED="1584856354206" MODIFIED="1584856354206" TEXT="According to theoretical predictions based on the local density approximation \cite{Chang16}, the contact constant $C_{LDA}$ of the depleted fraction should vary linearly with the peak condensate density $n_0$.  This was found in previous experiments\cite{Chang16}, although their scaling factor was out by a factor of $\sim$6.5. In Fig. \ref{C_inf}, we plot our measured values of $C$ and $n_0$, identifying the fit parameter $C$ with the contact constant $C_{LDA}$. A linear fit to the contact constant variation finds a gradient approximately 1.6 times more than the theory predicts, closer to theory than the previous measurement \cite{Chang16} (dotted line in Fig. \ref{C_inf}. This may suggest that there are physical effects beyond the local density approximation that need to be accounted for."/>
<node CREATED="1584856354209" ID="ID_1687514966" MODIFIED="1584856354209" TEXT="There are some possible explanations for the disagreement between LDA theory and experiment. This experiment requires resolution of a strong signal over nearly five orders of magnitude, careful calibration, and accurate parameter estimation with sparse and noisy data. Therefore, despite our best efforts systematic errors may be larger than estimated.  Some experimental effects that are potentially of concern are those that would distort the in-trap momentum profile during the experiment. For example, the in-trap momentum distribution might be affected by Penning ionization, which increases with the square of the condensate density. The mapping of the in-trap to free-particle momentum distribution for a fast (but not instantaneous) trap release in 3D has no analytic solution"/>
<node CREATED="1584856354211" ID="ID_378836007" MODIFIED="1584856354211" TEXT="and is challenging to accurately model numerically. Indeed, switch-off timescale may be relevant (compare \cite{Chang16} with \cite{Qu2016}), and we are now exploring this possibility. We have assumed that the RF transfer is momentum-independent, but this could be violated by inhomogeneities or transients in the magnetic field. The RF pulse may increase the Penning ionization rate in the depolarized sample, even though the density is low, which would alter the momentum profile. While applying the magnetic separation pulse, the condensates may scatter off each other."/>
<node CREATED="1584856354212" ID="ID_1686488471" MODIFIED="1584856354212" TEXT="Both of these effects could be investigated and minimized by extending the time after trap release before applying the transfer and separation pulses, allowing condensate densities to decrease \com{[is this something we&apos;re planning to do?  Doesn&apos;t seem so important to me]}."/>
<node CREATED="1584856354214" ID="ID_1225391356" MODIFIED="1584856354214" TEXT="Our experiment reproduces the results reported in \cite{Chang16} rather well, despite our trap switch-off being much slower. Actually it is probably the rate of change of cloud density - ours could be slow enough initially to distort the momentum profile"/>
<node CREATED="1584856354216" ID="ID_1344461052" MODIFIED="1584856354216" TEXT="This suggests that the originally observed result is indeed a real physical effect rather than experimental error.   The main difference we observe is that we measure $C_\infty$ coefficients that are much closer to the values predicted by Bogoliubov LDA theory, although there is still a minor quantitative disagreement. Hopefully our result will stimulate new theoretical interest in developing an explanation of why the quantum depletion tails can be observed after an interacting expansion, as well as try to resolve the discrepancy with theory."/>
<node CREATED="1584856354217" ID="ID_1152828092" MODIFIED="1584856354217" TEXT="A possible future experimental extension is to outcouple atoms using a broadened Raman transition.  This would have the benefit of moving the outcoupled atoms through the cloud rapidly, minimising the effects of repulsive inter-atomic interactions that normally affect the outcoupled profiles.  This should shed some light on whether interactions during trap switch off are the origin of the momentum tails. One could test the importance of particle scattering or Penning ionization by delaying the Rabi transfer to the $M_J = 0$ state, but this could increase vulnerability to stray magnetic fields \com{[is this something we&apos;re planning to do?  Doesn&apos;t seem so important to me, but if we think it is maybe we should just do it?]} {If what we observe is genuine quantum depletion, then it would be unchanged if the wait periods were extended. Relatively simple, assuming the expt is stable...}. Also, it may be possible to interpolate between existing results and the adiabatic transfer as described in  to demonstrate the adiabatic vanishing of the depleted fractio, which we are investigating now."/>
<node CREATED="1584856354219" ID="ID_644802089" MODIFIED="1584856354219" TEXT="- There may still be errors in the analysis. The fitting procedure        apparently produces a good fit, but it may be possible to get        indistinguishable or better fits by fixing the exponent of the power law        to be some  $\alpha\neq 4$ . This would challenge the assertion that the        cause of the observed profile is in fact quantum depletion. Assuming the        observed data does follow a power law, statistical fluctuations in the        high-momentum region become amplified by the  $k^4$  scaling procedure        and could introduce further error in the estimated Tan constant.        {blue}{Y-error bars are computed in a fairly ad-hoc way, so ours and Chang maybe drastically under-reported...)}"/>
<node CREATED="1584856354221" ID="ID_1154327101" MODIFIED="1584856354221" TEXT="Reliably        estimating the parameters of a power-law distribution is        nontrivial\cite{Clauset2009}, and the robustness of the fitting method        above has not been exhaustively tested. The LDA prediction is        essentially that the single-particle wavefunctions, hence the        single-particle probability distribution over momentum, are affected by        many-body effects. One computes the single-particle probability density        by dividing the condensate density by the number of particles (hence the         $N_0$  term in the LDA), and then the problem of extracting the contact        parameter from the data is an exercise in statistical parameter        estimation. As shown by Clauset et al \cite{Clauset2009}, fitting these        functions tends to produce incorrect estimates of parameters. The method        outlined in Clauset was proven to asymptotically converge with        probability 1 to the correct fit parameters of a power law distribution,        but would need to be extended to derive a maximum likelihood estimator        for a power law overlaid on a constant background."/>
</node>
<node CREATED="1584856354225" FOLDED="true" ID="ID_733781482" MODIFIED="1584857032325" POSITION="right" TEXT="% \section{Articles}">
<node CREATED="1584856354227" FOLDED="true" ID="ID_1571378500" MODIFIED="1584856358125" TEXT="\cite{Makotyn}">
<node CREATED="1584856354228" MODIFIED="1584856354228" TEXT="Strongly-interacting systems like neutron stars and High-T        superconductors are cool. Liquid Helium was the first discovered but        hard to probe, so ultracold gases have stepped up instead."/>
<node CREATED="1584856354230" MODIFIED="1584856354230" TEXT="This paper did not observe the expected  $k^{-4}$  tail, which would be        expected to arise from two-body short-range interactions. The amplitude        of this tail is the parameter known as the contact (ref 33); they do        concede the tail may exist below their sensitivity as their SNR is bad        at high momentum. The unitary experimental conditions might also lead to three-body interactions affecting the tails.        Check: Did they observe in-trap or after release?"/>
</node>
<node CREATED="1584856354232" FOLDED="true" ID="ID_1536819984" MODIFIED="1584856358126" TEXT="\cite{PStext}">
<node CREATED="1584856354233" MODIFIED="1584856354233" TEXT="Quantum depletion in a harmonic trap given by"/>
<node CREATED="1584856354234" MODIFIED="1584856354234" TEXT="\[\frac{\delta N}{N_0} = \frac{5\sqrt{\pi}}{8} \sqrt{a^3 n(0)}\] Which"/>
<node CREATED="1584856354235" MODIFIED="1584856354235" TEXT="is fixed by the gas parameter (number density) in the centre of the"/>
<node CREATED="1584856354236" MODIFIED="1584856354236" TEXT="trap. This conflicts with the result quoted below!"/>
<node CREATED="1584856354237" MODIFIED="1584856354237" TEXT="Strongly-interacting systems like neutron stars and High-T superconductors are cool. Liquid Helium was the first discovered but hard to probe, so ultracold gases have stepped up instead."/>
<node CREATED="1584856354239" MODIFIED="1584856354239" TEXT="This paper did not observe the expected $k^{-4}$ tail, which would be expected to arise from two-body short-range interactions. The amplitude of this tail is the parameter known as the contact (ref 33); they do concede the tail may exist below their sensitivity as their SNR is bad at high momentum. The unitary experimental conditions might also lead to three-body interactions affecting the tails."/>
<node CREATED="1584856354241" MODIFIED="1584856354241" TEXT="Check: Did they observe in-trap or after release?"/>
<node CREATED="1584856354242" MODIFIED="1584856354242" TEXT="\section{From PSText:}"/>
<node CREATED="1584856354243" MODIFIED="1584856354243" TEXT="Quantum depletion in a harmonic trap given by"/>
<node CREATED="1584856354245" MODIFIED="1584856354245" TEXT="$$\frac{\delta N}{N_0} = \frac{5\sqrt{\pi}}{8} \sqrt{a^3 n(0)}$$"/>
<node CREATED="1584856354246" MODIFIED="1584856354246" TEXT="Which is fixed by the gas parameter (number density) in the centre of the trap. This conflicts with the result quoted below!"/>
</node>
<node CREATED="1584856354247" FOLDED="true" ID="ID_1999245057" MODIFIED="1584856358126" TEXT="\cite{Muller}">
<node CREATED="1584856354248" MODIFIED="1584856354248" TEXT="The authors explicitly compute the quantum depletion contribution to the"/>
<node CREATED="1584856354249" MODIFIED="1584856354249" TEXT="momentum distribution in external potentials. The so-called `potential"/>
<node CREATED="1584856354250" MODIFIED="1584856354250" TEXT="depletion&apos; is a small correction to the homogeneous depletion. The"/>
<node CREATED="1584856354251" MODIFIED="1584856354251" TEXT="Penrose-Onsager criterion is only relevant for homogeneous condensates,"/>
<node CREATED="1584856354252" MODIFIED="1584856354252" TEXT="hence this paper&apos;s use of Bogoliubov theory to determine the one-body"/>
<node CREATED="1584856354253" MODIFIED="1584856354253" TEXT="density matrix. This means writing the atom field as a mean-field plus"/>
<node CREATED="1584856354255" MODIFIED="1584856354255" TEXT="perturbation, which gives another criterion for condensation in"/>
<node CREATED="1584856354256" MODIFIED="1584856354256" TEXT="non-homogeneous condensates. The momentum distribution similarly splits"/>
<node CREATED="1584856354257" MODIFIED="1584856354257" TEXT="into">
<node CREATED="1584856354258" MODIFIED="1584856354258" TEXT="$n_\textbf{k} = |\Phi_{\textbf{k}}|^2 + \langle \delta \Psi_\textbf{k}^\dagger \delta \Psi_\textbf{k}\rangle = n_{c\textbf{k}} + \delta n_\textbf{k}$ ,"/>
</node>
<node CREATED="1584856354260" MODIFIED="1584856354260" TEXT="contributions from the condensed and non-condensed fraction"/>
<node CREATED="1584856354261" MODIFIED="1584856354261" TEXT="respectively. In section 4 of the paper, the quantum depletion is"/>
<node CREATED="1584856354263" MODIFIED="1584856354263" TEXT="computed. The authors note that, as shown here, the population of the"/>
<node CREATED="1584856354264" MODIFIED="1584856354264" TEXT="zero-momentum state is not a good indicator of BEC in homogeneous"/>
<node CREATED="1584856354265" MODIFIED="1584856354265" TEXT="systems. That is, the number of particles in a nonzero momentum state is"/>
<node CREATED="1584856354266" MODIFIED="1584856354266" TEXT="NOT a measure of the depletion; the integral of the momentum"/>
<node CREATED="1584856354267" MODIFIED="1584856354267" TEXT="fluctuations about the mean-field, however, is."/>
<node CREATED="1584856354268" MODIFIED="1584856354268" TEXT="The quantum depletion is a finite non-condensed fraction at zero"/>
<node CREATED="1584856354269" MODIFIED="1584856354269" TEXT="temperature, arising from quantum fluctuations around the mean-field"/>
<node CREATED="1584856354270" MODIFIED="1584856354270" TEXT="approximation to the condensate. The deformation of the condensate by"/>
<node CREATED="1584856354272" MODIFIED="1584856354272" TEXT="the mean-field term in the GP equation does not lead to depletion. The"/>
<node CREATED="1584856354273" MODIFIED="1584856354273" TEXT="authors comment that the depleted fraction may be \emph{less}, and not"/>
<node CREATED="1584856354275" MODIFIED="1584856354275" TEXT="\emph{more} quantum than the condensate. Nonetheless: the depletion that"/>
<node CREATED="1584856354275" MODIFIED="1584856354275" TEXT="follows is the quantum depletion as opposed to the thermal depletion: It"/>
<node CREATED="1584856354276" MODIFIED="1584856354276" TEXT="is given by integrating the momentum fluctuations"/>
<node CREATED="1584856354277" MODIFIED="1584856354277" TEXT="\[\delta n = L^{-d} \sum_{\textbf{k}} \delta n_{\textbf{k}}\]"/>
<node CREATED="1584856354278" MODIFIED="1584856354278" TEXT="The Bogoliubov approximation is justified whenever  $n a_{s}^3$  is"/>
<node CREATED="1584856354278" MODIFIED="1584856354278" TEXT="small, i.e.~low density or weak scattering, when the depleted fraction"/>
<node CREATED="1584856354279" MODIFIED="1584856354279" TEXT="is small. In this case, in three dimensions, the depleted fraction is">
<node CREATED="1584856354280" MODIFIED="1584856354280" TEXT="$8(n a_s ^3)^{1/2} / 3 \pi^{1/2}$  in terms of the s-wave scattering"/>
</node>
<node CREATED="1584856354281" MODIFIED="1584856354281" TEXT="length, or  $n\xi^d &gt;&gt;1$ , with the healing"/>
<node CREATED="1584856354281" MODIFIED="1584856354281" TEXT="length $\xi = \hbar/\sqrt{2mgn_c}$  and  $g=4\pi \hbar^2 a_s/m$ ."/>
<node CREATED="1584856354282" MODIFIED="1584856354282" TEXT="The potential depletion turns out to be (small and) proportional to the"/>
<node CREATED="1584856354283" MODIFIED="1584856354283" TEXT="homegenous depletion. The most relevant result here is the depleted"/>
<node CREATED="1584856354284" MODIFIED="1584856354284" TEXT="fraction expression given above - there are no results given for"/>
<node CREATED="1584856354284" MODIFIED="1584856354284" TEXT="potential depletion in a harmonic trap, although one could use their"/>
<node CREATED="1584856354285" MODIFIED="1584856354285" TEXT="methods to compute this."/>
<node CREATED="1584856354286" MODIFIED="1584856354286" TEXT="N.B. This paper also computes the momentum distribution and depletion of"/>
<node CREATED="1584856354286" MODIFIED="1584856354286" TEXT="a condensate in a lattice, of interest to the upstairs experiment."/>
<node CREATED="1584856354287" MODIFIED="1584856354287" TEXT="The authors explicitly compute the quantum depletion contribution to the momentum distribution in external potentials. The so-called `potential depletion&apos; is a small correction to the homogeneous depletion. The Penrose-Onsager criterion is only relevant for homogeneous condensates, hence this paper&apos;s use of Bogoliubov theory to determine the one-body density matrix. This means writing the atom field as a mean-field plus perturbation, which gives another criterion for condensation in non-homogeneous condensates. The momentum distribution similarly splits into $n_\textbf{k} = |\Phi_{\textbf{k}}|^2 + \langle \delta \Psi_\textbf{k}^\dagger \delta \Psi_\textbf{k}\rangle = n_{c\textbf{k}} + \delta n_\textbf{k}$, contributions from the condensed and non-condensed fraction respectively. In section 4 of the paper, the quantum depletion is computed. The authors note that, as shown here, the population of the zero-momentum state is not a good indicator of BEC in homogeneous systems. That is, the number of particles in a nonzero momentum state is NOT a measure of the depletion; the integral of the momentum fluctuations about the mean-field, however, is."/>
</node>
<node CREATED="1584856354289" FOLDED="true" ID="ID_1089482722" MODIFIED="1584856358126" TEXT="\cite{sirjean}">
<node CREATED="1584856354290" MODIFIED="1584856354290" TEXT="The authors find that the ionization rate is almost solely responsible"/>
<node CREATED="1584856354291" MODIFIED="1584856354291" TEXT="for the decay of the confined condensate. They characterize the two- and"/>
<node CREATED="1584856354291" MODIFIED="1584856354291" TEXT="three-body contributions to the ionization loss rate, and find that"/>
<node CREATED="1584856354292" MODIFIED="1584856354292" TEXT="quantum depletion makes a significant contribution to the three-body"/>
<node CREATED="1584856354293" MODIFIED="1584856354293" TEXT="rate. The two- and three-body rates should be proportional to  $a^2$"/>
<node CREATED="1584856354294" MODIFIED="1584856354294" TEXT="and  $a^3$  respectively. The two-body rate they found was well-fitted"/>
<node CREATED="1584856354294" MODIFIED="1584856354294" TEXT="for the by a quadratic, but the three-body rate was found to be">
<node CREATED="1584856354295" MODIFIED="1584856354295" TEXT="$L\approx L_{20} (\frac{a}{20})^3 (1-0.21\frac{a-20}{20})$ , where they"/>
</node>
<node CREATED="1584856354296" MODIFIED="1584856354296" TEXT="assumed  $a=20$ nm (wrong), and it&apos;s not clear what the subscript 20 on"/>
<node CREATED="1584856354297" MODIFIED="1584856354297" TEXT="the L means. This paragraph is quite vague and has no citations, but if"/>
<node CREATED="1584856354298" MODIFIED="1584856354298" TEXT="correct suggests quantum depletion matters to collision rates. Their"/>
<node CREATED="1584856354298" MODIFIED="1584856354298" TEXT="fitted rates for two- and three-body collisions are of order 10E-14"/>
<node CREATED="1584856354299" MODIFIED="1584856354299" TEXT="cm $^3$ /sec and 10E-26 cm $^6$ /sec respectively. They state that their"/>
<node CREATED="1584856354301" MODIFIED="1584856354301" TEXT="assumed detector efficiency means a=10nm would require additional loss"/>
<node CREATED="1584856354302" MODIFIED="1584856354302" TEXT="mechanisms for half the losses, or imply an overestimate of the detector"/>
<node CREATED="1584856354303" MODIFIED="1584856354303" TEXT="efficiency. They quote an estimated 40 - ! So given the recent"/>
<node CREATED="1584856354304" MODIFIED="1584856354304" TEXT="measurements of scattering length, that seems very likely. (then again"/>
<node CREATED="1584856354304" MODIFIED="1584856354304" TEXT="they were detecting ions, not neutral atoms)"/>
<node CREATED="1584856354305" MODIFIED="1584856354305" TEXT="The atom number was measured by MCP. To avoid saturation, they lower the"/>
<node CREATED="1584856354306" MODIFIED="1584856354306" TEXT="MCP gain and record the signal in analog mode with a 400 $\mu s$  time"/>
<node CREATED="1584856354307" MODIFIED="1584856354307" TEXT="constant. They also leave their RF knife on at the end of a sequence and"/>
<node CREATED="1584856354308" MODIFIED="1584856354308" TEXT="maintain a very low thermal fraction."/>
<node CREATED="1584856354308" MODIFIED="1584856354308" TEXT="The authors find that the ionization rate is almost solely responsible for the decay of the confined condensate. They characterize the two- and three-body contributions to the ionization loss rate, and find that quantum depletion makes a significant contribution to the three-body rate. The two- and three-body rates should be proportional to $a^2$ and $a^3$ respectively. The two-body rate they found was well-fitted for the by a quadratic, but the three-body rate was found to be $L\approx L_{20} (\frac{a}{20})^3 (1-0.21\frac{a-20}{20})$, where they assumed $a=20$nm (wrong), and it&apos;s not clear what the subscript 20 on the L means. This paragraph is quite vague and has no citations, but if correct suggests quantum depletion matters to collision rates. Their fitted rates for two- and three-body collisions are of order 10E-14 cm$^3$/sec and 10E-26 cm$^6$/sec respectively. They state that their assumed detector efficiency means a=10nm would require additional loss mechanisms for half the losses, or imply an overestimate of the detector efficiency. They quote an estimated 40 - ! So given the recent measurements of scattering length, that seems very likely. (then again they were detecting ions, not neutral atoms)"/>
<node CREATED="1584856354310" MODIFIED="1584856354310" TEXT="The atom number was measured by MCP. To avoid saturation, they lower the MCP gain and record the signal in analog mode with a 400$\mu s$ time constant. They also leave their RF knife on at the end of a sequence and maintain a very low thermal fraction."/>
</node>
<node CREATED="1584856354311" FOLDED="true" ID="ID_1120501709" MODIFIED="1584856358126" TEXT="\cite{Lopes}">
<node CREATED="1584856354312" MODIFIED="1584856354312" TEXT="The authors measure quantum depletion in a homogeneous condensate. By"/>
<node CREATED="1584856354313" MODIFIED="1584856354313" TEXT="using a Feshbach resonance to tune the interactions, they are able to"/>
<node CREATED="1584856354314" MODIFIED="1584856354314" TEXT="control the depleted fraction. They measure the condensed fraction by"/>
<node CREATED="1584856354315" MODIFIED="1584856354315" TEXT="Bragg momentum spectroscopy. The results are qualitatively similar to"/>
<node CREATED="1584856354315" MODIFIED="1584856354315" TEXT="theory, however the theory at T=0 predicts lower quantum depletion than"/>
<node CREATED="1584856354316" MODIFIED="1584856354316" TEXT="was observed at finite temperatures. The thermal depletion also"/>
<node CREATED="1584856354317" MODIFIED="1584856354317" TEXT="populates the high-momentum tails and is not scattered out by the Bragg"/>
<node CREATED="1584856354318" MODIFIED="1584856354318" TEXT="process Their measurements are consistent with a small nonzero"/>
<node CREATED="1584856354319" MODIFIED="1584856354319" TEXT="temperature, consistent with their trap depth but they do not quote"/>
<node CREATED="1584856354319" MODIFIED="1584856354319" TEXT="doing actual thermometry. 15 -  and 20 -  statistical and systematic"/>
<node CREATED="1584856354320" MODIFIED="1584856354320" TEXT="error."/>
<node CREATED="1584856354321" MODIFIED="1584856354321" TEXT="In theory referenced, depletion of a homogeneous condensate is found to"/>
<node CREATED="1584856354321" MODIFIED="1584856354321" TEXT="be proportional to  $\sqrt{na^3}$  and valid for  $na^3&lt;\approx 10^-3$ ."/>
<node CREATED="1584856354322" MODIFIED="1584856354322" TEXT="Refs 15-17 measure depletion by using lattices to increase interactions,"/>
<node CREATED="1584856354323" MODIFIED="1584856354323" TEXT="and through expansion of dilute gas in 18 (i.e.~the paper we are"/>
<node CREATED="1584856354324" MODIFIED="1584856354324" TEXT="concerned with)"/>
<node CREATED="1584856354325" MODIFIED="1584856354325" TEXT="Authors use K-39 BEC and separate the BEC from high-momentum components"/>
<node CREATED="1584856354325" MODIFIED="1584856354325" TEXT="by Bragg two-photon process. Demonstrated dependence on scattering"/>
<node CREATED="1584856354326" MODIFIED="1584856354326" TEXT="length by Feshbach resonance and showed that depleted fraction depends"/>
<node CREATED="1584856354327" MODIFIED="1584856354327" TEXT="(reversibly) on scattering length."/>
<node CREATED="1584856354327" MODIFIED="1584856354327" TEXT="See refs 8, 9, for a connection to superconducitivity, superfluidity and"/>
<node CREATED="1584856354328" MODIFIED="1584856354328" TEXT="condensation. Side note: Connection of superfluidity to BEC was proposed"/>
<node CREATED="1584856354329" MODIFIED="1584856354329" TEXT="by Londin and Tisza."/>
<node CREATED="1584856354330" MODIFIED="1584856354330" TEXT="The authors measure quantum depletion in a homogeneous condensate. By using a Feshbach resonance to tune the interactions, they are able to control the depleted fraction. They measure the condensed fraction by Bragg momentum spectroscopy. The results are qualitatively similar to theory, however the theory at T=0 predicts lower quantum depletion than was observed at finite temperatures. The thermal depletion also populates the high-momentum tails and is not scattered out by the Bragg process Their measurements are consistent with a small nonzero temperature, consistent with their trap depth but they do not quote doing actual thermometry. 15 -  and 20 -  statistical and systematic error."/>
<node CREATED="1584856354331" MODIFIED="1584856354331" TEXT="In theory referenced, depletion of a homogeneous condensate is found to be proportional to $\sqrt{na^3}$ and valid for $na^3&lt;\approx 10^-3$. Refs 15-17 measure depletion by using lattices to increase interactions, and through expansion of dilute gas in 18 (i.e. the paper we are concerned with)"/>
<node CREATED="1584856354333" MODIFIED="1584856354333" TEXT="Authors use K-39 BEC and separate the BEC from high-momentum components by Bragg two-photon process. Demonstrated dependence on scattering length by Feshbach resonance and showed that depleted fraction depends (reversibly) on scattering length."/>
<node CREATED="1584856354334" MODIFIED="1584856354334" TEXT="See refs 8, 9, for a connection to superconducitivity, superfluidity and condensation."/>
<node CREATED="1584856354335" MODIFIED="1584856354335" TEXT="Side note: Connection of superfluidity to BEC was proposed by Londin and Tisza."/>
</node>
<node CREATED="1584856354336" FOLDED="true" ID="ID_899222512" MODIFIED="1584856358127" TEXT="\cite{Qu}">
<node CREATED="1584856354338" MODIFIED="1584856354338" TEXT="Theoretical study of time dependence of density and momentum"/>
<node CREATED="1584856354339" MODIFIED="1584856354339" TEXT="distribution of expanding gases, includding Bose case. They show that"/>
<node CREATED="1584856354340" MODIFIED="1584856354340" TEXT="the  $k^{-4}$  tal vanishes for large expansion times, in conflict with"/>
<node CREATED="1584856354341" MODIFIED="1584856354341" TEXT="the work of Chang et al."/>
<node CREATED="1584856354342" MODIFIED="1584856354342" TEXT="Suggestive links between short-range wavefunction behaviour and"/>
<node CREATED="1584856354343" MODIFIED="1584856354343" TEXT="thermodynamics via Tan contact (ref 1-7). Ref 1 for Tan defn. Ref 11-12,"/>
<node CREATED="1584856354343" MODIFIED="1584856354343" TEXT="measure momentum tail after expansion by tuning out interactions."/>
<node CREATED="1584856354344" MODIFIED="1584856354344" TEXT="Claim: Momentum distribution affected by interactions during expansion,"/>
<node CREATED="1584856354345" MODIFIED="1584856354345" TEXT="which is expected from the ballistic relation given the momentum"/>
<node CREATED="1584856354346" MODIFIED="1584856354346" TEXT="distribution. Expansion dynamics of momenta smaller than the inverse"/>
<node CREATED="1584856354347" MODIFIED="1584856354347" TEXT="healing length are well studied (by scaling relations or hydrodynamic"/>
<node CREATED="1584856354348" MODIFIED="1584856354348" TEXT="approx) but higher momentum not so. Section II and the conclusion are"/>
<node CREATED="1584856354349" MODIFIED="1584856354349" TEXT="the only interesting parts."/>
<node CREATED="1584856354350" MODIFIED="1584856354350" TEXT="Theoretical study of time dependence of density and momentum distribution of expanding gases, includding Bose case. They show that the $k^{-4}$ tal vanishes for large expansion times, in conflict with the work of Chang et al."/>
<node CREATED="1584856354351" MODIFIED="1584856354351" TEXT="Suggestive links between short-range wavefunction behaviour and thermodynamics via Tan contact (ref 1-7). Ref 1 for Tan defn. Ref 11-12, measure momentum tail after expansion by tuning out interactions."/>
<node CREATED="1584856354353" MODIFIED="1584856354353" TEXT="Claim: Momentum distribution affected by interactions during expansion, which is expected from the ballistic relation given the momentum distribution. Expansion dynamics of momenta smaller than the inverse healing length are well studied (by scaling relations or hydrodynamic approx) but higher momentum not so. Section II and the conclusion are the only interesting parts."/>
<node CREATED="1584856354354" MODIFIED="1584856354354" TEXT="The contact evolves as $C(t) = \int d\textbf{r} (16\pi ^2 \rho^2(\textbf{r},t)a^2)$ where $a$ is the s-wave scattering length and the integrand is the local contact density at equilibrium (from Bogoliubov theory). They use the scaling transformation from hydrodynamic theory to examine the evolution of the contact, which shows it decays with $C_0 /(\omega{ho} t)^3$, where $C_0$ is the initial contact. They open their argument with ``The adiabatic ansatz is expected to hold&apos;&apos; - seems dodgy."/>
<node CREATED="1584856354356" MODIFIED="1584856354356" TEXT="The fourth-power tail is observed in the section on Fermi gases, but is ruled out by arguing that it implies infrared divergence. (Recall Stringari comment - you have a natural cutoff which prevents this? But this is in thermodynamic limit maybe?) - the fourth-power tail also vanishes explicitly in the two-body case, but there&apos;s no strong result here!"/>
<node CREATED="1584856354000" FOLDED="true" ID="ID_88117766" MODIFIED="1584856898594" TEXT="% \com{Re-reading Qu et al the argument seems to be:">
<node CREATED="1584856354001" ID="ID_982892802" MODIFIED="1584856354001" TEXT="Qu et al \cite{Qu2016} claim that the depleted fraction should not be visible in the asymptotic momentum distribution by the following logic: Given the contact parameter is proportional to the integral of the squared density, one can use the hydrodynamic expansion of the BEC to show that the contact parameter tends to zero during expansion. This may be true for the expanding condensate, but (semiclassically thinking) the high-momentum particles would actually leave, hence decouple from, the condensate, and remain visible in the asymptotic density distribution)"/>
<node CREATED="1584856354010" ID="ID_1108214749" MODIFIED="1584856354010" TEXT="The mapping of the in-trap to free-particle momentum distribution for a        fast (but not instantaneous) trap release in 3D has no analytic solution        and is challenging to accurately model numerically. Indeed, switch-off        timescale may be relevant (compare \begin{equation}Chang16\end{equation} with \begin{equation}Qu2016\end{equation})."/>
<node CREATED="1584856354026" ID="ID_377707265" MODIFIED="1584856354026" TEXT="he contact evolves as $C(t) = \int d\textbf{r} (16\pi ^2 \rho^2(\textbf{r},t)a^2)$  where         $a$  is the s-wave scattering length and the integrand is the local        contact density at equilibrium (from Bogoliubov theory). They use the        scaling transformation from hydrodynamic theory to examine the evolution        of the contact, which shows it decays with  $C_0 /(\omega{ho} t)^3$ ,        where  $C_0$  is the initial contact. They open their argument with         ``The adiabatic ansatz is expected to hold&apos;&apos; - seems dodgy."/>
<node CREATED="1584856354028" ID="ID_1921766835" MODIFIED="1584856354028" TEXT="The fourth-power tail is observed in the section on Fermi gases, but is        ruled out by arguing that it implies infrared divergence. (Recall        Stringari comment - you have a natural cutoff which prevents this? But        this is in thermodynamic limit maybe?) - the fourth-power tail also        vanishes explicitly in the two-body case, but there&apos;s no strong result        here!"/>
<node CREATED="1584856354040" ID="ID_1820379649" MODIFIED="1584856896875" TEXT="N.B. This paper also computes the momentum distribution and depletion of a condensate in a lattice, of interest to the upstairs experiment."/>
</node>
</node>
</node>
</node>
</map>
